# Generated by Django 5.2.5 on 2025-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Размер наценки в рублях', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Наценка',
                'verbose_name_plural': 'Наценки',
                'db_table': 'markup',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=10)),
                ('variant', models.CharField(blank=True, max_length=20, null=True)),
                ('storage', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'iPhone',
                'verbose_name_plural': 'iPhone',
                'ordering': ['generation', 'variant', 'storage', 'color'],
                'unique_together': {('generation', 'variant', 'storage', 'color', 'country', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('configuration', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['brand', 'category', 'name'],
                'unique_together': {('name', 'brand', 'category', 'configuration', 'country')},
            },
        ),
    ]
