# Generated by Django 5.2.5 on 2025-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=20)),
                ('variant', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('memory', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MacBook',
                'verbose_name_plural': 'MacBook',
                'ordering': ['generation', 'variant', 'size', 'memory', 'storage', 'color'],
                'unique_together': {('generation', 'variant', 'size', 'memory', 'storage', 'color', 'country')},
            },
        ),
    ]
