# Generated by Django 5.2.5 on 2025-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_ipad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('case_material', models.CharField(blank=True, max_length=30, null=True)),
                ('case_color', models.CharField(max_length=30)),
                ('band_type', models.CharField(blank=True, max_length=50, null=True)),
                ('band_color', models.CharField(blank=True, max_length=50, null=True)),
                ('band_size', models.CharField(blank=True, max_length=10, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apple Watch',
                'verbose_name_plural': 'Apple Watch',
                'ordering': ['series', 'size', 'case_color', 'band_type'],
                'unique_together': {('series', 'size', 'case_color', 'band_type', 'band_color', 'band_size', 'connectivity', 'country')},
            },
        ),
    ]
