# Generated by Django 5.1.5 on 2025-09-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_applewatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('generation', models.CharField(max_length=20)),
                ('features', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(max_length=30)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AirPods',
                'verbose_name_plural': 'AirPods',
                'ordering': ['model', 'generation', 'features', 'color'],
                'unique_together': {('model', 'generation', 'features', 'color', 'year', 'country')},
            },
        ),
        migrations.CreateModel(
            name='iMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('chip', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('memory', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'iMac',
                'verbose_name_plural': 'iMac',
                'ordering': ['model', 'chip', 'size', 'memory', 'storage', 'color'],
                'unique_together': {('model', 'chip', 'size', 'memory', 'storage', 'color', 'country')},
            },
        ),
    ]
