# Generated by Django 5.1.5 on 2025-09-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_add_imac_airpods_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplePencil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='Apple Pencil', max_length=30)),
                ('generation', models.CharField(max_length=20)),
                ('connector', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apple Pencil',
                'verbose_name_plural': 'Apple Pencil',
                'ordering': ['generation', 'connector'],
                'unique_together': {('model', 'generation', 'connector', 'country')},
            },
        ),
    ]
